### ISSUE TITLE
localStorage persisting across sessions

### ISSUE THREAD

**Issue by stevegrossi** [elixir-wallaby/wallaby#274] opened 2017-07-13 10:40 UTC
In the latest version of Walaby (0.17.0), I believe I'm seeing the contents of `localStorage` persist across Wallaby's phantomjs sessions, despite [PR #93](https://github.com/keathley/wallaby/pull/93) which intended to separate localStorage between phantomjs sessions.

I've created a minimal test case in this repo: https://github.com/stevegrossi/wallaby_test

## Steps to Reproduce

I generated a brand new phoenix app with the default route going to `PageController.index`

On that page I have a bit of JavaScript that writes the contents of `localStorage` to the page, and then sets `'foo'` to `'bar'`:

```html
<script>
  const container = document.querySelector('#localstorage');
  const localstorageContents = "foo = " + localStorage.getItem('foo');
  container.innerText = localstorageContents;
  localStorage.setItem('foo', 'bar');
</script>
```

The idea being that if `localStorage` is empty, we can expect `foo = null` but if `foo` is set from a previous test run, we'll see `foo = bar`.

I set up Wallaby according to [the README](https://github.com/keathley/wallaby/blob/master/README.md#setup). My only departure from those instructions was not to add `async: true` to my tests, because in order to test `localStorage` persisting across tests I needed them to run serially.

Finally, I have two identical Wallaby feature tests that visit the index page and assert that `foo = null` was written to the page:

```elixir
IO.puts "session.id: #{session.id}"

session
|> visit("/")
|> assert_has(css("#localstorage", text: "foo = null"))
```

I also `puts` the session ID in order to confirm they're using different phantomjs sessoins. When run individually both tests pass:

```
steve@wallaby_test mix test test/features/page_one_test.exs
session.id: a1729160-67ae-11e7-8935-75b4a57c6225
.

Finished in 1.4 seconds
1 test, 0 failures

Randomized with seed 480326
steve@wallaby_test mix test test/features/page_two_test.exs
session.id: a58affd0-67ae-11e7-8fec-e7d5317a2964
.

Finished in 1.4 seconds
1 test, 0 failures

Randomized with seed 279952
```

But when run together with `mix test test/features`, the second fails, presumably because the page contains `foo = bar` from the previous session's `localStorage.set`, and not the expected `foo = null`:

```
steve@wallaby_test mix test test/features
session.id: a9911ec0-67ae-11e7-9d90-15727110d3bb
.session.id: a9acbd10-67ae-11e7-9d90-15727110d3bb


  1) test localstorage is empty a the start of the test (WallabyTest.PageOneTest)
     test/features/page_one_test.exs:6
     ** (Wallaby.ExpectationNotMet) Expected to find 1, visible element that matched the css '#localstorage' but 0, visible elements were found.

     stacktrace:
       test/features/page_one_test.exs:11: (test)

Finished in 4.4 seconds
2 tests, 1 failure
```

**Comment by keathley** [comment] 2017-07-13 13:29
Thanks for the great writeup @stevegrossi :+1:. I'll take a look and see if I can reproduce this locally.

**Comment by stevegrossi** [comment] 2017-07-13 14:17
Thanks! I should mention I have a perfectly valid workaround in my app: simply logging out after each feature test so that the `token` I persist in `localStorage` goes away.

And thanks for your hard work on Wallaby!

**Comment by keathley** [comment] 2018-07-11 14:14
We should confirm that this isn't broken in chrome. There are known sanitization issues with phantom but I'm planning on replacing phantom with chrome as the default driver. If chrome does not share this issue then I think we're safe to close it.

**Comment by mhanberg** [comment] 2019-02-26 15:05
It looks like this is fine in chrome: https://github.com/mhanberg/wallaby_test

Tested with elixir 1.7, wallaby 0.22 and chromedriver 2.46.628411

**Comment by mhanberg** [comment] 2020-12-15 16:19
Closing due to issue being related to phantomjs, which is now removed.

**Closed by mhanberg** 2020-12-15 16:19 UTC
Labels: Kind:Bug, Level:Intermediate
